# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'AllAboutGoogleMaps' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AllAboutGoogleMaps
pod 'GoogleMaps'
pod 'GooglePlaces'

end
